name: deploy cloud run service

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "273.0.0"
          # service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker
      - uses: devmasx/cached-docker-build-push@v0.1.1
        with:
          image_name: gcr.io/docker-rails-258302/cloud-run-base
      - run: |
          gcloud run deploy cloud-run-base \
            --project docker-rails-258302 \
            --image gcr.io/docker-rails-258302/cloud-run-base \
            --platform managed \
            --region us-central1
      
